### ISSUE TITLE
Import : Stop import quand erreur ConvertCBZ

### ISSUE THREAD

**Issue by slucky31** [slucky31/mycomicsmanager#166]
2022-05-31 06:51:49 [INF] CreateTempDirectory -- Création du répertoire temporaire : /tmp/4hqc4q0p.qh2
2022-05-31 06:51:49 [INF] ConvertComicFileToCbz -- Extraction des images
2022-05-31 06:51:49 [INF] ConvertComicFileToCbz -- ExtractImagesFromCbz
2022-05-31 06:51:49 [ERR] ExtractImagesFromCbz -- Erreur lors de l'extraction de l'archive /mcm/tmp/Transmetropolitan.T05.cbz
2022-05-31 06:52:10 [WRN]  -- Le fichier /mcm/tmp/Transmetropolitan.T05.cbz a été déplacé dans /mcm/libs/errors/Transmetropolitan.T05.cbz
2022-05-31 06:52:10 [ERR] ConvertComicFileToCbz -- Erreur lors de l'extraction des images à partir du fichier CBZ /mcm/tmp/Transmetropolitan.T05.cbz
2022-05-31 06:52:10 [ERR] ConvertToCbz -- Erreur lors de la conversion en CBZ
MyComicsManagerApi.Exceptions.ComicIoException: Erreur lors de l'extraction de l'archive. Consulter le répertoire errors.
 ---> System.IO.InvalidDataException: End of Central Directory record could not be found.
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
   at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding)
   at System.IO.Compression.ZipFile.ExtractToDirectory(String sourceArchiveFileName, String destinationDirectoryName, Encoding entryNameEncoding, Boolean overwriteFiles)
   at System.IO.Compression.ZipFile.ExtractToDirectory(String sourceArchiveFileName, String destinationDirectoryName, Boolean overwriteFiles)
   at MyComicsManagerApi.Services.ComicFileService.ExtractImagesFromCbz(String comicEbookPath, String tempDir) in /src/MyComicsManagerApi/Services/ComicFileService.cs:line 387
   --- End of inner exception stack trace ---
   at MyComicsManagerApi.Services.ComicFileService.ExtractImagesFromCbz(String comicEbookPath, String tempDir) in /src/MyComicsManagerApi/Services/ComicFileService.cs:line 393
   at MyComicsManagerApi.Services.ComicFileService.ConvertComicFileToCbz(Comic comic) in /src/MyComicsManagerApi/Services/ComicFileService.cs:line 168
   at MyComicsManagerApi.Services.ComicService.ConvertToCbz(Comic comic) in /src/MyComicsManagerApi/Services/ComicService.cs:line 95
2022-05-31 06:52:10 [INF] ConvertToCbz -- comic.ImportStatus = ERROR
2022-05-31 06:52:10 [ERR] MoveComic -- Erreur lors du déplacement du fichier /mcm/tmp/Transmetropolitan.T05.cbz vers /mcm/libs/bd/Transmetropolitan.T05.cbz
2022-05-31 06:52:10 [WRN]  -- Le fichier /mcm/libs/errors/Transmetropolitan.T05.cbz existe déjà
2022-05-31 06:52:10 [WRN]  -- Il va être renommé en Transmetropolitan.T05-Duplicate.cbz
2022-05-31 06:52:10 [ERR] ConvertToCbz -- Erreur lors du déplacement du fichier /mcm/tmp/Transmetropolitan.T05.cbz vers /mcm/libs/bd/Transmetropolitan.T05.cbz
2022-05-31 06:52:11 [ERROR] (Hangfire.AutomaticRetryAttribute) Failed to process the job '629380572272afe7a9a1035d': an exception occurred.
System.NullReferenceException
Object reference not set to an instance of an object.
   at MyComicsManagerApi.Services.ComicFileService.GetComicEbookPath(Comic comic, PathType pathType) in /src/MyComicsManagerApi/Services/ComicFileService.cs:line 595
   at MyComicsManagerApi.Services.ComicFileService.HasComicInfoInComicFile(Comic comic) in /src/MyComicsManagerApi/Services/ComicFileService.cs:line 489
   at MyComicsManagerApi.Services.ComicService.Import(Comic comic) in /src/MyComicsManagerApi/Services/ComicService.cs:line 152

**Comment by slucky31** [comment]
try
            {
                _comicFileService.ConvertComicFileToCbz(comic);
                comic.ImportStatus = ImportStatus.CBZ_CONVERTED;
            }
            catch (Exception e)
            {
                Log.Here().Error(e, "Erreur lors de la conversion en CBZ");
                comic.ImportStatus = ImportStatus.ERROR;
                return null;
            }

- [x] Il faut persister quand on change le statut ! : Une méthode doit être réalisée pour changer le statut, logé et persisté.
- [x] Vérifier que Le fichier doit être déplacé dans errors quand il y a une erreur
