### ISSUE TITLE
Create Lib : Access denied

### ISSUE THREAD

**Issue by slucky31** [slucky31/mycomicsmanager#675]
23:27:31.861
[21:27:31 WRN] Unhandled exception rendering component: Access to the path '/mcm' is denied.
 
23:27:31.861
System.UnauthorizedAccessException: Access to the path '/mcm' is denied.
 
23:27:31.861
---> System.IO.IOException: Permission denied
 
23:27:31.861
   --- End of inner exception stack trace ---
 
23:27:31.861
   at System.IO.FileSystem.CreateParentsAndDirectory(String fullPath, UnixFileMode unixCreateMode)
 
23:27:31.861
   at System.IO.FileSystem.CreateDirectory(String fullPath, UnixFileMode unixCreateMode)
 
23:27:31.861
   at System.IO.Directory.CreateDirectory(String path)
 
23:27:31.861
   at Persistence.LocalStorage.LibraryLocalStorage.Create(String folderName) in /source/Persistence/LocalStorage/LibraryLocalStorage.cs:line 31
 
23:27:31.862
   at Application.Libraries.Create.CreateLibraryCommandHandler.Handle(CreateLibraryCommand request, CancellationToken cancellationToken) in /source/Application/Libraries/Create/CreateLibraryCommandHandler.cs:line 31
 
23:27:31.862
   at Web.Services.LibrariesService.Create(String name) in /source/Web/Services/LibrariesService.cs:line 23
 
23:27:31.862
   at Web.Components.Pages.Libraries.LibraryForm.CreateOrUpdateLibrary() in /source/Web/Components/Pages/Libraries/LibraryForm.razor.cs:line 35
 
23:27:31.862
   at Web.Components.Pages.Libraries.LibraryForm.<BuildRenderTree>b__15_12() in /source/Web/Components/Pages/Libraries/LibraryForm.razor:line 38
 
23:27:31.862
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
 
23:27:31.862
   at MudBlazor.MudBaseButton.OnClickHandler(MouseEventArgs ev)
 
23:27:31.862
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

**Comment by slucky31** [comment]
Pour le moment la création des lob se fait dans /home/app/mcm/libs !
Il faudra ajouter à terme le volume pour pointer vers le disque dur !
